import { useState, useRef, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { request } from '../api/api';
import {
  Send, Wifi, WifiOff, MessageSquare,
  Lightbulb, CornerDownRight, Loader2, CheckCircle2,
  AlertTriangle, XCircle, Database,
} from 'lucide-react';

/* ── Helpers ── */

// Returns true if the SQL is a real query worth showing, not an internal fallback
function isRealSQL(sql) {
  if (!sql) return false;
  const s = sql.trim().toUpperCase();
  // Hide internal no-schema / no-connection fallback queries
  if (s.includes("'NO DATABASE SCHEMA AVAILABLE'")) return false;
  if (s.includes("'NO DATABASE CONNECTION")) return false;
  if (s.includes('AS MESSAGE') && s.startsWith("SELECT '")) return false;
  return true;
}

// Extract a clean, friendly error string from raw error messages
function friendlyError(content) {
  if (!content) return null;
  const c = content.toString();
  if (c.includes('No database connection in context') || c.includes('No database schema')) {
    return {
      title: 'No database selected',
      detail: 'Please select a connection from the dropdown above before asking a question.',
      icon: Database,
      type: 'warn',
    };
  }
  if (c.toLowerCase().includes('network') || c.toLowerCase().includes('fetch')) {
    return {
      title: 'Connection problem',
      detail: 'Could not reach the server. Check that the backend and agent services are running.',
      icon: WifiOff,
      type: 'error',
    };
  }
  if (c.toLowerCase().startsWith('error:') || c.toLowerCase().includes('failed')) {
    return {
      title: 'Something went wrong',
      detail: c.replace(/^error:\s*/i, ''),
      icon: XCircle,
      type: 'error',
    };
  }
  return null;
}

/* ── Sub-components ── */

function SystemBanner({ content }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: '0.6rem',
      padding: '0.55rem 0.9rem', borderRadius: '8px',
      background: 'rgba(18,77,84,0.08)', border: '1px solid rgba(18,77,84,0.18)',
      fontSize: '0.82rem', color: 'var(--teal)', fontWeight: 500,
      margin: '0.25rem 0',
    }}>
      <CheckCircle2 size={14} strokeWidth={2.5} style={{ flexShrink: 0 }} />
      {content}
    </div>
  );
}

function AIOfflineBanner({ content }) {
  // Parse metrics out of the notice string for a cleaner display
  const rowsMatch   = content.match(/Found (\d+) results/);
  const colsMatch   = content.match(/(\d+) columns/);
  const rows  = rowsMatch?.[1];
  const cols  = colsMatch?.[1];

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: '0.65rem',
      padding: '0.75rem 1rem', borderRadius: '10px',
      background: 'rgba(249,116,75,0.08)', border: '1px solid rgba(249,116,75,0.25)',
      fontSize: '0.83rem', color: 'var(--navy)',
      margin: '0.3rem 0',
    }}>
      <AlertTriangle size={15} strokeWidth={2} color="var(--orange)" style={{ marginTop: 2, flexShrink: 0 }} />
      <div>
        <div style={{ fontWeight: 600, color: 'var(--orange)', marginBottom: '0.2rem' }}>
          AI engine is offline — using basic query mode
        </div>
        <div style={{ color: 'var(--text-secondary)', lineHeight: 1.5 }}>
          Ollama (local AI) is not running. Results are generated by rule-based SQL only.
          {rows && cols && (
            <span style={{ marginLeft: 6, color: 'var(--teal)', fontWeight: 600 }}>
              Found {rows} rows · {cols} columns.
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function ErrorCard({ err }) {
  const Icon = err.icon;
  const isWarn = err.type === 'warn';
  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: '0.65rem',
      padding: '0.85rem 1rem', borderRadius: '10px',
      background: isWarn ? 'rgba(249,116,75,0.07)' : 'rgba(220,53,69,0.07)',
      border: `1px solid ${isWarn ? 'rgba(249,116,75,0.25)' : 'rgba(220,53,69,0.25)'}`,
      maxWidth: '90%', margin: '0.25rem 0',
    }}>
      <Icon size={16} strokeWidth={2} color={isWarn ? 'var(--orange)' : '#dc3545'} style={{ marginTop: 2, flexShrink: 0 }} />
      <div>
        <div style={{ fontWeight: 700, fontSize: '0.88rem', color: isWarn ? 'var(--orange)' : '#c0392b', marginBottom: '0.2rem' }}>
          {err.title}
        </div>
        <div style={{ fontSize: '0.83rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
          {err.detail}
        </div>
      </div>
    </div>
  );
}

/* ── Main Chat component ── */
export default function Chat() {
  const [draft, setDraft]               = useState('');
  const [isLoading, setIsLoading]       = useState(false);
  const [historyLoaded, setHistoryLoaded] = useState(false);

  // ── Messages: loaded from MongoDB on mount, cached in sessionStorage within session ──
  const [messages, setMessages] = useState(() => {
    try {
      const saved = sessionStorage.getItem('chat-messages');
      return saved ? JSON.parse(saved) : [];
    } catch { return []; }
  });

  const [savedConnections, setSavedConnections] = useState([]);

  // ── Selected connection: persisted in sessionStorage within session ──
  const [connection, setConnection] = useState(() => {
    try {
      const saved = sessionStorage.getItem('chat-connection');
      return saved ? JSON.parse(saved) : null;
    } catch { return null; }
  });

  const bottomRef = useRef(null);

  // Sync messages to sessionStorage whenever they change
  useEffect(() => {
    try { sessionStorage.setItem('chat-messages', JSON.stringify(messages)); }
    catch { /* quota exceeded – ignore */ }
  }, [messages]);

  // Sync connection to sessionStorage whenever it changes
  useEffect(() => {
    try {
      if (connection) sessionStorage.setItem('chat-connection', JSON.stringify(connection));
      else sessionStorage.removeItem('chat-connection');
    } catch { }
  }, [connection]);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  // ── On mount: load THIS user's chat history from MongoDB (source of truth) ──
  useEffect(() => {
    const cachedRaw = sessionStorage.getItem('chat-messages');
    const cached = cachedRaw ? JSON.parse(cachedRaw) : [];

    // If sessionStorage already has messages for this session, skip the DB fetch
    if (cached.length > 0) {
      setHistoryLoaded(true);
      return;
    }

    // Load from MongoDB — only messages belonging to this logged-in user
    request('/chat/history')
      .then(data => {
        if (Array.isArray(data) && data.length > 0) {
          // Convert DB records into the chat message format the UI understands
          const dbMessages = [];
          data.forEach(item => {
            dbMessages.push({ role: 'user', content: item.question });
            dbMessages.push({
              role: 'assistant',
              content: item.analysis || null,
              sql: item.sql,
              columns: item.columns,
              rows: item.rows,
              row_count: item.row_count,
              chart_config: item.chart_config,
              recommendations: item.recommendations,
              followups: item.followups,
              decision: item.decision,
              notice: null,
              loading: false,
            });
          });
          setMessages(dbMessages);
        }
      })
      .catch(() => {})
      .finally(() => setHistoryLoaded(true));
  }, []);

  // ── Load connections for this user only ──
  useEffect(() => {
    request('/databases')
      .then(data => {
        const conns = Array.isArray(data) ? data : [];
        setSavedConnections(conns);
        // Re-validate the stored connection still exists after refresh
        if (connection) {
          const stillExists = conns.find(c => c.id?.toString() === connection.id?.toString());
          if (!stillExists) {
            setConnection(null);
            sessionStorage.removeItem('chat-connection');
          }
        }
      })
      .catch(() => {});
  }, []);

  function handleSelectConnection(e) {
    const connId = e.target.value;
    if (!connId) {
      setConnection(null);
      setMessages(prev => [...prev, { role: 'system', content: 'Disconnected from database.' }]);
      return;
    }
    const selected = savedConnections.find(c => c.id?.toString() === connId);
    if (selected) {
      setConnection(selected);
      setMessages(prev => [...prev, {
        role: 'system',
        content: `Connected to ${selected.database} @ ${selected.host}`,
      }]);
    }
  }

  async function handleSend(e) {
    e.preventDefault();
    const question = draft.trim();
    if (!question) return;
    setDraft('');
    setMessages(prev => [
      ...prev,
      { role: 'user', content: question },
      { role: 'assistant', content: null, loading: true },
    ]);
    setIsLoading(true);
    try {
      const data = await request('/chat', {
        method: 'POST',
        body: JSON.stringify({ question, connection }),
      });
      setMessages(prev => {
        const next = [...prev];
        next[next.length - 1] = {
          role: 'assistant',
          content: data.analysis || null,
          sql: data.sql,
          columns: data.columns,
          rows: data.rows,
          row_count: data.row_count,
          chart_config: data.chart_config,
          recommendations: data.recommendations,
          followups: data.followups,
          decision: data.decision,
          notice: data.notice || null,   // AI offline notice
          loading: false,
        };
        return next;
      });
    } catch (err) {
      setMessages(prev => {
        const next = [...prev];
        next[next.length - 1] = {
          role: 'assistant',
          content: `Error: ${err.message}`,
          loading: false,
        };
        return next;
      });
    } finally {
      setIsLoading(false);
    }
  }

  const noConn = savedConnections.length === 0;

  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 120px)', gap: '0.75rem' }}>

      {/* ── Header + connection bar ── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem' }}>
        <div className="page-header" style={{ marginBottom: 0 }}>
          <h2>AI Chat</h2>
          <p>Ask questions about your data in plain English</p>
        </div>
        <div className={`chat-connection-bar ${connection ? 'connected' : 'disconnected'}`} style={{ marginBottom: 0, minWidth: '340px', flexShrink: 0 }}>
          {connection
            ? <Wifi size={15} strokeWidth={2} style={{ flexShrink: 0 }} />
            : <WifiOff size={15} strokeWidth={2} style={{ flexShrink: 0 }} />}
          <span>{connection ? `${connection.database} @ ${connection.host}` : 'No database connected'}</span>
          <select className="chat-select" onChange={handleSelectConnection} value={connection ? connection.id : ''}>
            <option value="">— Select Connection —</option>
            {savedConnections.map(c => (
              <option key={c.id} value={c.id}>{c.name || c.database} ({c.host})</option>
            ))}
          </select>
        </div>
      </div>

      {/* ── Messages area ── */}
      <div className="card" style={{ flex: 1, overflowY: 'auto', padding: '1rem' }}>
        <div className="chat-messages">

          {/* Loading history from DB */}
          {messages.length === 0 && !historyLoaded && (
            <div className="chat-empty">
              <Loader2 size={28} color="var(--teal)" strokeWidth={1.5}
                style={{ marginBottom: '0.75rem', animation: 'spin 1s linear infinite' }} />
              <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem' }}>Loading your chat history…</p>
            </div>
          )}

          {/* Empty state — only shown after history is confirmed empty */}
          {messages.length === 0 && historyLoaded && (
            <div className="chat-empty">
              <MessageSquare size={36} color="var(--text-muted)" strokeWidth={1.2} style={{ marginBottom: '0.75rem' }} />
              <h3>Start a conversation</h3>
              <p>Ask a question about your database in plain English</p>
              <p style={{ marginTop: '0.5rem', fontSize: '0.8rem' }}>
                Example: <em>&quot;Show the top 10 customers by revenue&quot;</em>
              </p>
            </div>
          )}

          {messages.map((msg, i) => {
            /* ── System connection banner ── */
            if (msg.role === 'system') {
              return <SystemBanner key={i} content={msg.content} />;
            }

            /* ── User bubble ── */
            if (msg.role === 'user') {
              return (
                <div key={i} className="bubble-row user">
                  <div className="bubble user">{msg.content}</div>
                </div>
              );
            }

            /* ── Assistant message ── */
            const errInfo = !msg.loading ? friendlyError(msg.content) : null;
            const showSQL = isRealSQL(msg.sql);

            // Detect AI-offline notice (could be in content or notice field)
            const noticeText = msg.notice || (
              typeof msg.content === 'string' && msg.content.toLowerCase().includes('ai engine') && msg.content.toLowerCase().includes('offline')
                ? msg.content : null
            );
            // Clean display content (don't show raw notice string as a bubble)
            const displayContent = noticeText ? null
              : errInfo ? null
              : msg.content;

            return (
              <div key={i}>
                {/* Loading spinner */}
                {msg.loading && (
                  <div className="bubble-row assistant">
                    <div className="bubble assistant">
                      <Loader2 size={16} strokeWidth={2} style={{ animation: 'spin 1s linear infinite' }} />
                    </div>
                  </div>
                )}

                {/* AI offline notice intentionally hidden per user request */}

                {/* Error card */}
                {!msg.loading && errInfo && <ErrorCard err={errInfo} />}

                {/* Normal assistant text bubble */}
                {!msg.loading && displayContent && (
                  <div className="bubble-row assistant">
                    <div className="bubble assistant">{displayContent}</div>
                  </div>
                )}

                {/* SQL intentionally hidden — users don't need to see raw SQL */}

                {/* Results table */}
                {!msg.loading && msg.columns?.length > 0 && msg.rows?.length > 0 && (
                  <div className="results-table-wrap" style={{ maxWidth: '100%' }}>
                    <div className="results-meta">{msg.row_count} row(s) returned</div>
                    <table className="results-table">
                      <thead><tr>{msg.columns.map(col => <th key={col}>{col}</th>)}</tr></thead>
                      <tbody>
                        {msg.rows.slice(0, 20).map((row, ri) => (
                          <tr key={ri}>{row.map((cell, ci) => <td key={ci}>{String(cell ?? '')}</td>)}</tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {/* Recommendations */}
                {!msg.loading && msg.recommendations?.length > 0 && (
                  <div className="recommendations-box">
                    <div className="recommendations-title">
                      <Lightbulb size={13} strokeWidth={2} style={{ display: 'inline', marginRight: 5 }} />
                      Insights
                    </div>
                    {msg.recommendations.map((r, ri) => (
                      <div key={ri} className="recommendations-item">• {r}</div>
                    ))}
                  </div>
                )}

                {/* Follow-up chips */}
                {!msg.loading && msg.followups?.length > 0 && (
                  <div className="followups-wrap">
                    <div className="followups-label">
                      <CornerDownRight size={12} strokeWidth={2} style={{ display: 'inline', marginRight: 4 }} />
                      You might also ask
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
                      {msg.followups.map((q, qi) => (
                        <button key={qi} className="followup-chip" onClick={() => setDraft(q)}>{q}</button>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
          <div ref={bottomRef} />
        </div>
      </div>

      {/* ── Input bar ── */}
      <form onSubmit={handleSend} className="chat-input-bar">
        <input
          id="chat-input"
          className="chat-input"
          value={draft}
          onChange={e => setDraft(e.target.value)}
          placeholder={noConn
            ? "Select a database connection above to start chatting…"
            : "Ask anything about your database…"}
          disabled={isLoading || noConn}
        />
        <button
          id="chat-send"
          type="submit"
          className="chat-send-btn"
          disabled={isLoading || !draft.trim() || noConn}
        >
          <Send size={16} strokeWidth={2.5} />
        </button>
      </form>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
